version: '3.8'

services:

  example-frontend:
    build: "./example-frontend"
    container_name: example-frontend
    ports:
      - 5000:5000
    # environment:
    #   - REACT_APP_BACKEND_URL="http://localhost:8080"


  example-backend:
    build: "./example-backend"
    container_name: example-backend
    ports:
      - 8080:8080
    # environment:
    #   - PORT=8080
    #   - REQUEST_ORIGIN="http://localhost:5000" Weird!!